### ISSUE TITLE
error opening squire config

### ISSUE THREAD

**Issue by layzsmurf** [Adirelle/Squire3#26]
Today I tried opening up the squire3 config with /squire and I got an error. I updated to the latest alpha - removed the saved variables file and yet the error persists:
--------------------------------------
20x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1803: AceConfigRegistry-3.0-15:ValidateOptionsTable(): Squire3.args.spells.args.spells.args.121827.name: expected a string or funcref, got 'nil'
[C]: ?
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:187: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:182>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:221: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:196>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:231: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:196>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:231: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:196>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:231: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:196>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:259: in function `ValidateOptionsTable'
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-15.lua:312: in function `app'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1803: in function `Open'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1896: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1894>
(tail call): ?
...
FrameXML\InterfaceOptionsFrame.lua:475: in function <FrameXML\InterfaceOptionsFrame.lua:424>
[C]: in function `InterfaceOptionsFrame_OpenToCategory'
!BlizzBugsSuck\BlizzBugsSuck.lua:92: in function <!BlizzBugsSuck\BlizzBugsSuck.lua:61>
[C]: in function `InterfaceOptionsFrame_OpenToCategory'
Squire3\Config.lua:347: in function `?'
FrameXML\ChatFrame.lua:4422: in function <FrameXML\ChatFrame.lua:4369>
[C]: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4076: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4115: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
nil

**Comment by layzsmurf** [comment]
editing Data.lua and removing the line (and the "," the line before)
----
 
 121827, "", 10, nil, nil -- Celerity Roll
---

enables me to open up the squire3 config again. I have a level 15 monk. Not sure if this breaks the config.

**Comment by 2ndHouse** [comment]
I have the same problem on my Rogue.
